/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationResponseDataObject } from './AccommodationResponseDataObject';
import {
    AccommodationResponseDataObjectFromJSON,
    AccommodationResponseDataObjectFromJSONTyped,
    AccommodationResponseDataObjectToJSON,
} from './AccommodationResponseDataObject';

/**
 * 
 * @export
 * @interface AccommodationResponse
 */
export interface AccommodationResponse {
    /**
     * 
     * @type {AccommodationResponseDataObject}
     * @memberof AccommodationResponse
     */
    data?: AccommodationResponseDataObject;
    /**
     * 
     * @type {object}
     * @memberof AccommodationResponse
     */
    meta?: object;
}

/**
 * Check if a given object implements the AccommodationResponse interface.
 */
export function instanceOfAccommodationResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationResponseFromJSON(json: any): AccommodationResponse {
    return AccommodationResponseFromJSONTyped(json, false);
}

export function AccommodationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : AccommodationResponseDataObjectFromJSON(json['data']),
        'meta': !exists(json, 'meta') ? undefined : json['meta'],
    };
}

export function AccommodationResponseToJSON(value?: AccommodationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AccommodationResponseDataObjectToJSON(value.data),
        'meta': value.meta,
    };
}

