/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationRequestData } from './AccommodationRequestData';
import {
    AccommodationRequestDataFromJSON,
    AccommodationRequestDataFromJSONTyped,
    AccommodationRequestDataToJSON,
} from './AccommodationRequestData';

/**
 * 
 * @export
 * @interface AccommodationRequest
 */
export interface AccommodationRequest {
    /**
     * 
     * @type {AccommodationRequestData}
     * @memberof AccommodationRequest
     */
    data: AccommodationRequestData;
}

/**
 * Check if a given object implements the AccommodationRequest interface.
 */
export function instanceOfAccommodationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function AccommodationRequestFromJSON(json: any): AccommodationRequest {
    return AccommodationRequestFromJSONTyped(json, false);
}

export function AccommodationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': AccommodationRequestDataFromJSON(json['data']),
    };
}

export function AccommodationRequestToJSON(value?: AccommodationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AccommodationRequestDataToJSON(value.data),
    };
}

