/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesRelatedDataInner
 */
export interface AccommodationPicturesDataInnerAttributesRelatedDataInner {
    /**
     * 
     * @type {number}
     * @memberof AccommodationPicturesDataInnerAttributesRelatedDataInner
     */
    id?: number;
    /**
     * 
     * @type {object}
     * @memberof AccommodationPicturesDataInnerAttributesRelatedDataInner
     */
    attributes?: object;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesRelatedDataInner interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesRelatedDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSON(json: any): AccommodationPicturesDataInnerAttributesRelatedDataInner {
    return AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesRelatedDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
    };
}

export function AccommodationPicturesDataInnerAttributesRelatedDataInnerToJSON(value?: AccommodationPicturesDataInnerAttributesRelatedDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'attributes': value.attributes,
    };
}

