/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesFolderDataAttributes } from './AccommodationPicturesDataInnerAttributesFolderDataAttributes';
import {
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderDataAttributes';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesFolderData
 */
export interface AccommodationPicturesDataInnerAttributesFolderData {
    /**
     * 
     * @type {number}
     * @memberof AccommodationPicturesDataInnerAttributesFolderData
     */
    id?: number;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributes}
     * @memberof AccommodationPicturesDataInnerAttributesFolderData
     */
    attributes?: AccommodationPicturesDataInnerAttributesFolderDataAttributes;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesFolderData interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesFolderData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFolderDataFromJSON(json: any): AccommodationPicturesDataInnerAttributesFolderData {
    return AccommodationPicturesDataInnerAttributesFolderDataFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFolderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesFolderData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesFromJSON(json['attributes']),
    };
}

export function AccommodationPicturesDataInnerAttributesFolderDataToJSON(value?: AccommodationPicturesDataInnerAttributesFolderData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'attributes': AccommodationPicturesDataInnerAttributesFolderDataAttributesToJSON(value.attributes),
    };
}

