/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInner } from './AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInner';
import {
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInner';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFiles
 */
export interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFiles {
    /**
     * 
     * @type {Array<AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInner>}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFiles
     */
    data?: Array<AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInner>;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesFolderDataAttributesFiles interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesFolderDataAttributesFiles(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesFromJSON(json: any): AccommodationPicturesDataInnerAttributesFolderDataAttributesFiles {
    return AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesFolderDataAttributesFiles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerFromJSON)),
    };
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesToJSON(value?: AccommodationPicturesDataInnerAttributesFolderDataAttributesFiles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerToJSON)),
    };
}

