/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInner } from './AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInner';
import {
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInner';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles
 */
export interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles {
    /**
     * 
     * @type {Array<AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInner>}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles
     */
    data?: Array<AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInner>;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesFromJSON(json: any): AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles {
    return AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerFromJSON)),
    };
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesToJSON(value?: AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRoles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerToJSON)),
    };
}

