/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesFolderDataAttributesParent } from './AccommodationPicturesDataInnerAttributesFolderDataAttributesParent';
import {
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderDataAttributesParent';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
 */
export interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    action?: string;
    /**
     * 
     * @type {any}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    actionParameters?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    subject?: string;
    /**
     * 
     * @type {any}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    properties?: any | null;
    /**
     * 
     * @type {any}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    conditions?: any | null;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesParent}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    role?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesParent}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    createdBy?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesParent}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes
     */
    updatedBy?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesFromJSON(json: any): AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes {
    return AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'actionParameters': !exists(json, 'actionParameters') ? undefined : json['actionParameters'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'properties': !exists(json, 'properties') ? undefined : json['properties'],
        'conditions': !exists(json, 'conditions') ? undefined : json['conditions'],
        'role': !exists(json, 'role') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json['role']),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json['createdBy']),
        'updatedBy': !exists(json, 'updatedBy') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json['updatedBy']),
    };
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesToJSON(value?: AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'actionParameters': value.actionParameters,
        'subject': value.subject,
        'properties': value.properties,
        'conditions': value.conditions,
        'role': AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value.role),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdBy': AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value.createdBy),
        'updatedBy': AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value.updatedBy),
    };
}

