/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesFolderData } from './AccommodationPicturesDataInnerAttributesFolderData';
import {
    AccommodationPicturesDataInnerAttributesFolderDataFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderData';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesFolder
 */
export interface AccommodationPicturesDataInnerAttributesFolder {
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderData}
     * @memberof AccommodationPicturesDataInnerAttributesFolder
     */
    data?: AccommodationPicturesDataInnerAttributesFolderData;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesFolder interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesFolder(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFolderFromJSON(json: any): AccommodationPicturesDataInnerAttributesFolder {
    return AccommodationPicturesDataInnerAttributesFolderFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesFolder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataFromJSON(json['data']),
    };
}

export function AccommodationPicturesDataInnerAttributesFolderToJSON(value?: AccommodationPicturesDataInnerAttributesFolder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AccommodationPicturesDataInnerAttributesFolderDataToJSON(value.data),
    };
}

