/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributes } from './AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributes';
import {
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributes';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData
 */
export interface AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData {
    /**
     * 
     * @type {number}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData
     */
    id?: number;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributes}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData
     */
    attributes?: AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributes;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataFromJSON(json: any): AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData {
    return AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesFromJSON(json['attributes']),
    };
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataToJSON(value?: AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'attributes': AccommodationPicturesDataInnerAttributesFolderDataAttributesFilesDataInnerAttributesCreatedByDataAttributesToJSON(value.attributes),
    };
}

