/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInner } from './AccommodationPicturesDataInner';
import {
    AccommodationPicturesDataInnerFromJSON,
    AccommodationPicturesDataInnerFromJSONTyped,
    AccommodationPicturesDataInnerToJSON,
} from './AccommodationPicturesDataInner';

/**
 * 
 * @export
 * @interface AccommodationPictures
 */
export interface AccommodationPictures {
    /**
     * 
     * @type {Array<AccommodationPicturesDataInner>}
     * @memberof AccommodationPictures
     */
    data?: Array<AccommodationPicturesDataInner>;
}

/**
 * Check if a given object implements the AccommodationPictures interface.
 */
export function instanceOfAccommodationPictures(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesFromJSON(json: any): AccommodationPictures {
    return AccommodationPicturesFromJSONTyped(json, false);
}

export function AccommodationPicturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPictures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AccommodationPicturesDataInnerFromJSON)),
    };
}

export function AccommodationPicturesToJSON(value?: AccommodationPictures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AccommodationPicturesDataInnerToJSON)),
    };
}

