/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Accommodation } from './Accommodation';
import {
    AccommodationFromJSON,
    AccommodationFromJSONTyped,
    AccommodationToJSON,
} from './Accommodation';

/**
 * 
 * @export
 * @interface AccommodationResponseDataObject
 */
export interface AccommodationResponseDataObject {
    /**
     * 
     * @type {number}
     * @memberof AccommodationResponseDataObject
     */
    id?: number;
    /**
     * 
     * @type {Accommodation}
     * @memberof AccommodationResponseDataObject
     */
    attributes?: Accommodation;
}

/**
 * Check if a given object implements the AccommodationResponseDataObject interface.
 */
export function instanceOfAccommodationResponseDataObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationResponseDataObjectFromJSON(json: any): AccommodationResponseDataObject {
    return AccommodationResponseDataObjectFromJSONTyped(json, false);
}

export function AccommodationResponseDataObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationResponseDataObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'attributes': !exists(json, 'attributes') ? undefined : AccommodationFromJSON(json['attributes']),
    };
}

export function AccommodationResponseDataObjectToJSON(value?: AccommodationResponseDataObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'attributes': AccommodationToJSON(value.attributes),
    };
}

