/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPictures } from './AccommodationPictures';
import {
    AccommodationPicturesFromJSON,
    AccommodationPicturesFromJSONTyped,
    AccommodationPicturesToJSON,
} from './AccommodationPictures';
import type { AccommodationPicturesDataInnerAttributesFolderDataAttributesParent } from './AccommodationPicturesDataInnerAttributesFolderDataAttributesParent';
import {
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderDataAttributesParent';

/**
 * 
 * @export
 * @interface Accommodation
 */
export interface Accommodation {
    /**
     * 
     * @type {string}
     * @memberof Accommodation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Accommodation
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof Accommodation
     */
    reviewScore?: number;
    /**
     * 
     * @type {AccommodationPictures}
     * @memberof Accommodation
     */
    pictures?: AccommodationPictures;
    /**
     * 
     * @type {string}
     * @memberof Accommodation
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof Accommodation
     */
    reviewsCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Accommodation
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Accommodation
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Accommodation
     */
    publishedAt?: Date;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesParent}
     * @memberof Accommodation
     */
    createdBy?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesParent}
     * @memberof Accommodation
     */
    updatedBy?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the Accommodation interface.
 */
export function instanceOfAccommodation(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationFromJSON(json: any): Accommodation {
    return AccommodationFromJSONTyped(json, false);
}

export function AccommodationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Accommodation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'location': !exists(json, 'Location') ? undefined : json['Location'],
        'reviewScore': !exists(json, 'ReviewScore') ? undefined : json['ReviewScore'],
        'pictures': !exists(json, 'Pictures') ? undefined : AccommodationPicturesFromJSON(json['Pictures']),
        'address': !exists(json, 'Address') ? undefined : json['Address'],
        'reviewsCount': !exists(json, 'ReviewsCount') ? undefined : json['ReviewsCount'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'publishedAt': !exists(json, 'publishedAt') ? undefined : (new Date(json['publishedAt'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json['createdBy']),
        'updatedBy': !exists(json, 'updatedBy') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json['updatedBy']),
    };
}

export function AccommodationToJSON(value?: Accommodation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Location': value.location,
        'ReviewScore': value.reviewScore,
        'Pictures': AccommodationPicturesToJSON(value.pictures),
        'Address': value.address,
        'ReviewsCount': value.reviewsCount,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'publishedAt': value.publishedAt === undefined ? undefined : (value.publishedAt.toISOString()),
        'createdBy': AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value.createdBy),
        'updatedBy': AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value.updatedBy),
    };
}

