/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesFolder } from './AccommodationPicturesDataInnerAttributesFolder';
import {
    AccommodationPicturesDataInnerAttributesFolderFromJSON,
    AccommodationPicturesDataInnerAttributesFolderFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderToJSON,
} from './AccommodationPicturesDataInnerAttributesFolder';
import type { AccommodationPicturesDataInnerAttributesFolderDataAttributesParent } from './AccommodationPicturesDataInnerAttributesFolderDataAttributesParent';
import {
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSONTyped,
    AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON,
} from './AccommodationPicturesDataInnerAttributesFolderDataAttributesParent';
import type { AccommodationPicturesDataInnerAttributesRelated } from './AccommodationPicturesDataInnerAttributesRelated';
import {
    AccommodationPicturesDataInnerAttributesRelatedFromJSON,
    AccommodationPicturesDataInnerAttributesRelatedFromJSONTyped,
    AccommodationPicturesDataInnerAttributesRelatedToJSON,
} from './AccommodationPicturesDataInnerAttributesRelated';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributes
 */
export interface AccommodationPicturesDataInnerAttributes {
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    alternativeText?: string;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    caption?: string;
    /**
     * 
     * @type {number}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    height?: number;
    /**
     * 
     * @type {any}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    formats?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    ext?: string;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    mime?: string;
    /**
     * 
     * @type {number}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    previewUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    provider?: string;
    /**
     * 
     * @type {any}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    providerMetadata?: any | null;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesRelated}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    related?: AccommodationPicturesDataInnerAttributesRelated;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolder}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    folder?: AccommodationPicturesDataInnerAttributesFolder;
    /**
     * 
     * @type {string}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    folderPath?: string;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    updatedAt?: Date;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesParent}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    createdBy?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent;
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesFolderDataAttributesParent}
     * @memberof AccommodationPicturesDataInnerAttributes
     */
    updatedBy?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributes interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFromJSON(json: any): AccommodationPicturesDataInnerAttributes {
    return AccommodationPicturesDataInnerAttributesFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'alternativeText': !exists(json, 'alternativeText') ? undefined : json['alternativeText'],
        'caption': !exists(json, 'caption') ? undefined : json['caption'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'formats': !exists(json, 'formats') ? undefined : json['formats'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'ext': !exists(json, 'ext') ? undefined : json['ext'],
        'mime': !exists(json, 'mime') ? undefined : json['mime'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'previewUrl': !exists(json, 'previewUrl') ? undefined : json['previewUrl'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'providerMetadata': !exists(json, 'provider_metadata') ? undefined : json['provider_metadata'],
        'related': !exists(json, 'related') ? undefined : AccommodationPicturesDataInnerAttributesRelatedFromJSON(json['related']),
        'folder': !exists(json, 'folder') ? undefined : AccommodationPicturesDataInnerAttributesFolderFromJSON(json['folder']),
        'folderPath': !exists(json, 'folderPath') ? undefined : json['folderPath'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json['createdBy']),
        'updatedBy': !exists(json, 'updatedBy') ? undefined : AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json['updatedBy']),
    };
}

export function AccommodationPicturesDataInnerAttributesToJSON(value?: AccommodationPicturesDataInnerAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'alternativeText': value.alternativeText,
        'caption': value.caption,
        'width': value.width,
        'height': value.height,
        'formats': value.formats,
        'hash': value.hash,
        'ext': value.ext,
        'mime': value.mime,
        'size': value.size,
        'url': value.url,
        'previewUrl': value.previewUrl,
        'provider': value.provider,
        'provider_metadata': value.providerMetadata,
        'related': AccommodationPicturesDataInnerAttributesRelatedToJSON(value.related),
        'folder': AccommodationPicturesDataInnerAttributesFolderToJSON(value.folder),
        'folderPath': value.folderPath,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'createdBy': AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value.createdBy),
        'updatedBy': AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value.updatedBy),
    };
}

