/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationListResponseDataItem } from './AccommodationListResponseDataItem';
import {
    AccommodationListResponseDataItemFromJSON,
    AccommodationListResponseDataItemFromJSONTyped,
    AccommodationListResponseDataItemToJSON,
} from './AccommodationListResponseDataItem';
import type { AccommodationListResponseMeta } from './AccommodationListResponseMeta';
import {
    AccommodationListResponseMetaFromJSON,
    AccommodationListResponseMetaFromJSONTyped,
    AccommodationListResponseMetaToJSON,
} from './AccommodationListResponseMeta';

/**
 * 
 * @export
 * @interface AccommodationListResponse
 */
export interface AccommodationListResponse {
    /**
     * 
     * @type {Array<AccommodationListResponseDataItem>}
     * @memberof AccommodationListResponse
     */
    data?: Array<AccommodationListResponseDataItem>;
    /**
     * 
     * @type {AccommodationListResponseMeta}
     * @memberof AccommodationListResponse
     */
    meta?: AccommodationListResponseMeta;
}

/**
 * Check if a given object implements the AccommodationListResponse interface.
 */
export function instanceOfAccommodationListResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationListResponseFromJSON(json: any): AccommodationListResponse {
    return AccommodationListResponseFromJSONTyped(json, false);
}

export function AccommodationListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AccommodationListResponseDataItemFromJSON)),
        'meta': !exists(json, 'meta') ? undefined : AccommodationListResponseMetaFromJSON(json['meta']),
    };
}

export function AccommodationListResponseToJSON(value?: AccommodationListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AccommodationListResponseDataItemToJSON)),
        'meta': AccommodationListResponseMetaToJSON(value.meta),
    };
}

