/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesRelatedDataInner } from './AccommodationPicturesDataInnerAttributesRelatedDataInner';
import {
    AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSON,
    AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSONTyped,
    AccommodationPicturesDataInnerAttributesRelatedDataInnerToJSON,
} from './AccommodationPicturesDataInnerAttributesRelatedDataInner';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesFolderDataAttributesParent
 */
export interface AccommodationPicturesDataInnerAttributesFolderDataAttributesParent {
    /**
     * 
     * @type {AccommodationPicturesDataInnerAttributesRelatedDataInner}
     * @memberof AccommodationPicturesDataInnerAttributesFolderDataAttributesParent
     */
    data?: AccommodationPicturesDataInnerAttributesRelatedDataInner;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesFolderDataAttributesParent interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesFolderDataAttributesParent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSON(json: any): AccommodationPicturesDataInnerAttributesFolderDataAttributesParent {
    return AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesFolderDataAttributesParent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSON(json['data']),
    };
}

export function AccommodationPicturesDataInnerAttributesFolderDataAttributesParentToJSON(value?: AccommodationPicturesDataInnerAttributesFolderDataAttributesParent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': AccommodationPicturesDataInnerAttributesRelatedDataInnerToJSON(value.data),
    };
}

