/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccommodationPicturesDataInnerAttributesRelatedDataInner } from './AccommodationPicturesDataInnerAttributesRelatedDataInner';
import {
    AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSON,
    AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSONTyped,
    AccommodationPicturesDataInnerAttributesRelatedDataInnerToJSON,
} from './AccommodationPicturesDataInnerAttributesRelatedDataInner';

/**
 * 
 * @export
 * @interface AccommodationPicturesDataInnerAttributesRelated
 */
export interface AccommodationPicturesDataInnerAttributesRelated {
    /**
     * 
     * @type {Array<AccommodationPicturesDataInnerAttributesRelatedDataInner>}
     * @memberof AccommodationPicturesDataInnerAttributesRelated
     */
    data?: Array<AccommodationPicturesDataInnerAttributesRelatedDataInner>;
}

/**
 * Check if a given object implements the AccommodationPicturesDataInnerAttributesRelated interface.
 */
export function instanceOfAccommodationPicturesDataInnerAttributesRelated(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationPicturesDataInnerAttributesRelatedFromJSON(json: any): AccommodationPicturesDataInnerAttributesRelated {
    return AccommodationPicturesDataInnerAttributesRelatedFromJSONTyped(json, false);
}

export function AccommodationPicturesDataInnerAttributesRelatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationPicturesDataInnerAttributesRelated {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(AccommodationPicturesDataInnerAttributesRelatedDataInnerFromJSON)),
    };
}

export function AccommodationPicturesDataInnerAttributesRelatedToJSON(value?: AccommodationPicturesDataInnerAttributesRelated | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(AccommodationPicturesDataInnerAttributesRelatedDataInnerToJSON)),
    };
}

