/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccommodationListResponseMetaPagination
 */
export interface AccommodationListResponseMetaPagination {
    /**
     * 
     * @type {number}
     * @memberof AccommodationListResponseMetaPagination
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AccommodationListResponseMetaPagination
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof AccommodationListResponseMetaPagination
     */
    pageCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AccommodationListResponseMetaPagination
     */
    total?: number;
}

/**
 * Check if a given object implements the AccommodationListResponseMetaPagination interface.
 */
export function instanceOfAccommodationListResponseMetaPagination(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccommodationListResponseMetaPaginationFromJSON(json: any): AccommodationListResponseMetaPagination {
    return AccommodationListResponseMetaPaginationFromJSONTyped(json, false);
}

export function AccommodationListResponseMetaPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccommodationListResponseMetaPagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'pageCount': !exists(json, 'pageCount') ? undefined : json['pageCount'],
        'total': !exists(json, 'total') ? undefined : json['total'],
    };
}

export function AccommodationListResponseMetaPaginationToJSON(value?: AccommodationListResponseMetaPagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'pageCount': value.pageCount,
        'total': value.total,
    };
}

