/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadIdIdPostRequestFileInfo
 */
export interface UploadIdIdPostRequestFileInfo {
    /**
     * 
     * @type {string}
     * @memberof UploadIdIdPostRequestFileInfo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadIdIdPostRequestFileInfo
     */
    alternativeText?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadIdIdPostRequestFileInfo
     */
    caption?: string;
}

/**
 * Check if a given object implements the UploadIdIdPostRequestFileInfo interface.
 */
export function instanceOfUploadIdIdPostRequestFileInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UploadIdIdPostRequestFileInfoFromJSON(json: any): UploadIdIdPostRequestFileInfo {
    return UploadIdIdPostRequestFileInfoFromJSONTyped(json, false);
}

export function UploadIdIdPostRequestFileInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadIdIdPostRequestFileInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'alternativeText': !exists(json, 'alternativeText') ? undefined : json['alternativeText'],
        'caption': !exists(json, 'caption') ? undefined : json['caption'],
    };
}

export function UploadIdIdPostRequestFileInfoToJSON(value?: UploadIdIdPostRequestFileInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'alternativeText': value.alternativeText,
        'caption': value.caption,
    };
}

