/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersPermissionsRole
 */
export interface UsersPermissionsRole {
    /**
     * 
     * @type {number}
     * @memberof UsersPermissionsRole
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRole
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRole
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRole
     */
    type?: string;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsRole
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsersPermissionsRole
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the UsersPermissionsRole interface.
 */
export function instanceOfUsersPermissionsRole(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersPermissionsRoleFromJSON(json: any): UsersPermissionsRole {
    return UsersPermissionsRoleFromJSONTyped(json, false);
}

export function UsersPermissionsRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPermissionsRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function UsersPermissionsRoleToJSON(value?: UsersPermissionsRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

