/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersPermissionsPermissionsTreeValue } from './UsersPermissionsPermissionsTreeValue';
import {
    UsersPermissionsPermissionsTreeValueFromJSON,
    UsersPermissionsPermissionsTreeValueFromJSONTyped,
    UsersPermissionsPermissionsTreeValueToJSON,
} from './UsersPermissionsPermissionsTreeValue';

/**
 * 
 * @export
 * @interface UsersPermissionsRolesPostRequest
 */
export interface UsersPermissionsRolesPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolesPostRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolesPostRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPermissionsRolesPostRequest
     */
    type?: string;
    /**
     * 
     * @type {{ [key: string]: UsersPermissionsPermissionsTreeValue; }}
     * @memberof UsersPermissionsRolesPostRequest
     */
    permissions?: { [key: string]: UsersPermissionsPermissionsTreeValue; };
}

/**
 * Check if a given object implements the UsersPermissionsRolesPostRequest interface.
 */
export function instanceOfUsersPermissionsRolesPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersPermissionsRolesPostRequestFromJSON(json: any): UsersPermissionsRolesPostRequest {
    return UsersPermissionsRolesPostRequestFromJSONTyped(json, false);
}

export function UsersPermissionsRolesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPermissionsRolesPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'permissions': !exists(json, 'permissions') ? undefined : (mapValues(json['permissions'], UsersPermissionsPermissionsTreeValueFromJSON)),
    };
}

export function UsersPermissionsRolesPostRequestToJSON(value?: UsersPermissionsRolesPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'permissions': value.permissions === undefined ? undefined : (mapValues(value.permissions, UsersPermissionsPermissionsTreeValueToJSON)),
    };
}

