/* tslint:disable */
/* eslint-disable */
/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersPermissionsRole } from './UsersPermissionsRole';
import {
    UsersPermissionsRoleFromJSON,
    UsersPermissionsRoleFromJSONTyped,
    UsersPermissionsRoleToJSON,
} from './UsersPermissionsRole';

/**
 * 
 * @export
 * @interface UsersPost201Response
 */
export interface UsersPost201Response {
    /**
     * 
     * @type {number}
     * @memberof UsersPost201Response
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UsersPost201Response
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPost201Response
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPost201Response
     */
    provider?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPost201Response
     */
    confirmed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPost201Response
     */
    blocked?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UsersPost201Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UsersPost201Response
     */
    updatedAt?: Date;
    /**
     * 
     * @type {UsersPermissionsRole}
     * @memberof UsersPost201Response
     */
    role?: UsersPermissionsRole;
}

/**
 * Check if a given object implements the UsersPost201Response interface.
 */
export function instanceOfUsersPost201Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersPost201ResponseFromJSON(json: any): UsersPost201Response {
    return UsersPost201ResponseFromJSONTyped(json, false);
}

export function UsersPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPost201Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'confirmed': !exists(json, 'confirmed') ? undefined : json['confirmed'],
        'blocked': !exists(json, 'blocked') ? undefined : json['blocked'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'role': !exists(json, 'role') ? undefined : UsersPermissionsRoleFromJSON(json['role']),
    };
}

export function UsersPost201ResponseToJSON(value?: UsersPost201Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'username': value.username,
        'email': value.email,
        'provider': value.provider,
        'confirmed': value.confirmed,
        'blocked': value.blocked,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'role': UsersPermissionsRoleToJSON(value.role),
    };
}

